---
- hosts: all
  tasks:
    - name: Upgrade all installed packages
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install all Windows updates
      ansible.windows.win_updates:
        category_names: '*'
        reboot: yes
      when: ansible_facts['os_family'] == "Windows"
